### PR TITLE
Shrink logo and title on small screens

### PR DESCRIPTION
**Pull request by CurtisGreen**
The menu wraps to the other side on my phone so I'm having it shrink to an even smaller size when the screen width is less than 420px

Before:
image

After:
image

### CODE REVIEW

**Comment by cullam3n** [comment]
The dark mode icon, can that be moved up in the heading since it's not frozen?

**Comment by CurtisGreen** [comment]
> The dark mode icon, can that be moved up in the heading since it's not frozen?

The theme switcher is just floating separate from the navbar. I could put it in the navbar but it looks pretty visually distinct so might look weird. Can you give me an example of what you were thinking of?

**Comment by Schobbish** [comment]
I was kinda experimenting with making it look like this but working on alignment

Screenshot 2024-07-28 at 10 03 46 PM

Screenshot 2024-07-28 at 10 05 09 PM

**Comment by CurtisGreen** [comment]
@Schobbish Gotcha, lemme know if you need any help

**Pull request merged**
